import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { AlertTriangle, ArrowRight, BatteryCharging, Check, ChevronRight, ShieldCheck, Zap } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { Button, Field, Logo } from "../components/ui";
import { PublicHeader } from "../components/Shell";

const loginSchema = z.object({ email: z.string().email("이메일 형식을 확인하세요."), password: z.string().min(1, "비밀번호를 입력하세요.") });
type LoginValues = z.infer<typeof loginSchema>;
const signupSchema = z.object({ name: z.string().min(1, "이름을 입력하세요."), email: z.string().email("이메일 형식을 확인하세요."), phone: z.string().min(8, "전화번호를 입력하세요."), password: z.string().regex(/^(?=.*[A-Za-z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,}$/, "영문·숫자·특수문자를 포함한 8자 이상이어야 합니다."), agreed: z.boolean().refine((value) => value, "약관 동의가 필요합니다.") });
type SignupValues = z.infer<typeof signupSchema>;

function MiniTrend({ color = "#2563eb", points = "0,32 20,26 40,29 60,17 80,23 100,10 120,18" }: { color?: string; points?: string }) {
  return <svg className="mini-line" viewBox="0 0 120 40" preserveAspectRatio="none" aria-hidden="true"><polyline points={points} fill="none" stroke={color} strokeWidth="2.4" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

export function LandingPage() {
  const navigate = useNavigate();
  const [preview, setPreview] = useState<"monitor" | "anomaly" | "failsafe">("monitor");
  const openLogin = () => navigate("/login");
  const openSignUp = () => navigate("/signup");
  return <div className="public-page v3-public-page">
    <PublicHeader onLogin={openLogin} onSignUp={openSignUp} />
    <main>
      <section className="v3-hero"><div className="v3-hero-grid">
        <div className="v3-hero-copy"><span className="hero-pill"><span className="pulse-dot" />AI 열폭주 예측 · 실시간</span><h1><span>먼저 알고,</span><br />먼저 막는다.<span className="sr-only"> 배터리의 이상을 더 일찍 발견하세요.</span></h1><p>전압·전류·온도·SOC를 1초 단위로 수집하고, AI가 이상점수를 산출해 열폭주 징후를 사고 전에 먼저 경고합니다.</p><div className="hero-actions"><Button variant="primary" onClick={openLogin}>무료로 시작하기 <ArrowRight size={16} /></Button><Button variant="ghost" onClick={() => document.getElementById("preview")?.scrollIntoView({ behavior: "smooth" })}>라이브 데모 보기 <ChevronRight size={16} /></Button></div><div className="hero-signal-list"><span><i className="signal-dot temp" />온도</span><span><i className="signal-dot volt" />전압</span><span><i className="signal-dot curr" />전류</span><span><i className="signal-dot soc" />SOC</span></div></div>
        <div className="v3-hero-device"><div className="hero-device-shadow" /><div className="hero-device-panel cg-glass"><div className="hero-device-head"><span><i className="pulse-dot" />실시간 관제 중</span><b>PACK-001 · NCM-72Ah</b></div><div className="hero-device-body"><div className="hero-score"><small>현재 이상점수</small><div className="hero-gauge"><svg viewBox="0 0 200 110" aria-hidden="true"><path d="M10 100 A90 90 0 0 1 190 100" fill="none" stroke="rgba(20,23,25,.12)" strokeWidth="16" strokeLinecap="round" /><path d="M10 100 A90 90 0 0 1 190 100" fill="none" stroke="#EA580C" strokeWidth="16" strokeLinecap="round" strokeDasharray="104 280" /></svg><strong>58</strong><em>주의</em></div></div><div className="hero-metric-grid"><div className="metric-tone volt"><small>전압</small><strong>3.7V</strong><span /><MiniTrend color="#16a34a" /></div><div className="metric-tone curr"><small>전류</small><strong>2.4A</strong><span /><MiniTrend color="#0ea5e9" points="0,18 20,26 40,16 60,23 80,13 100,22 120,16" /></div><div className="metric-tone temp"><small>온도</small><strong>62.1°C</strong><span /><MiniTrend color="#ea580c" points="0,32 20,29 40,24 60,20 80,13 100,8 120,5" /></div><div className="metric-tone soc"><small>SOC</small><strong>73%</strong><span /><MiniTrend color="#7c3aed" points="0,14 20,17 40,15 60,19 80,18 100,22 120,20" /></div></div></div><div className="hero-device-trend"><svg viewBox="0 0 280 96" preserveAspectRatio="none" aria-label="이상점수 추세"><path d="M0 78 C38 66 58 74 82 58 S122 62 148 45 S190 56 218 35 S255 40 280 14" fill="none" stroke="#EA580C" strokeWidth="2.4" strokeLinecap="round" /><path d="M0 78 C38 66 58 74 82 58 S122 62 148 45 S190 56 218 35 S255 40 280 14 L280 96 L0 96Z" fill="#ea580c" fillOpacity=".08" /></svg></div></div></div>
      </div></section>

      <section id="how" className="v3-section v3-how"><div className="v3-section-heading"><span>HOW IT WORKS</span><h2>데이터 수집부터 자동 차단까지, 3단계</h2><p>사고를 막는 것은 순간이 아니라, 이 세 단계가 매초 반복되는 흐름입니다.</p></div><div className="v3-step-grid"><div className="v3-step cg-glass"><small>01</small><span className="step-icon"><Zap size={24} /></span><h3>1초 단위 실시간 수집</h3><p>전압·전류·온도·SOC를 초 단위로 끊김 없이 수집해 이상 징후를 놓치지 않습니다.</p></div><div className="v3-step cg-glass"><small>02</small><span className="step-icon"><AlertTriangle size={24} /></span><h3>AI 열폭주 조기 경고</h3><p>수집된 신호로 이상점수를 산출하고, 열폭주로 이어지기 전 위험 징후를 먼저 알립니다.</p></div><div className="v3-step cg-glass"><small>03</small><span className="step-icon"><ShieldCheck size={24} /></span><h3>위험 시 자동 릴레이 차단</h3><p>임계값 초과 시 Fail-Safe 인터락이 릴레이를 자동으로 차단해 사고를 예방합니다.</p></div></div></section>

      <section id="preview" className="v3-section v3-preview"><div className="v3-section-heading"><span>PRODUCT PREVIEW</span><h2>화면으로 직접 확인하세요</h2><p>모니터링부터 이상탐지, 자동 차단까지 — 셀가드가 실제로 보여주는 화면입니다.</p></div><div className="preview-tabs" role="tablist"><button className={preview === "monitor" ? "active" : ""} onClick={() => setPreview("monitor")} role="tab">실시간 모니터링</button><button className={preview === "anomaly" ? "active" : ""} onClick={() => setPreview("anomaly")} role="tab">AI 이상탐지</button><button className={preview === "failsafe" ? "active" : ""} onClick={() => setPreview("failsafe")} role="tab">자동 차단</button></div><div className="preview-window cg-glass"><div className="preview-window-bar"><i /><i /><i /></div>{preview === "monitor" && <div className="preview-content preview-monitor"><div className="preview-pack cg-surface"><strong>배터리 팩 #001</strong><div className="preview-pack-body"><span className="preview-battery"><BatteryCharging size={38} /></span><div><p><span>전압</span><b>3.7V</b></p><p><span>전류</span><b>2.4A</b></p><p><span>SOC</span><b>73%</b></p></div></div></div><div className="preview-chart cg-surface"><strong>실시간 온도 추세</strong><svg viewBox="0 0 280 96" preserveAspectRatio="none"><path d="M0 72 C35 68 50 70 78 60 S120 65 147 50 S188 52 215 32 S250 35 280 16" fill="none" stroke="#16a34a" strokeWidth="2.5" /></svg></div></div>}{preview === "anomaly" && <div className="preview-content preview-monitor"><div className="preview-pack cg-surface preview-risk"><div className="preview-card-heading"><strong>AI 열폭주 예측 리스크</strong><span>향후 6시간</span></div><div className="risk-number">64<em>위험도 경고</em></div><div className="contribution"><p><span>온도 상승률</span><b>기여 64%</b></p><span><i style={{ width: "64%" }} /></span><p><span>전류 변화량</span><b>기여 22%</b></p><span><i style={{ width: "22%" }} /></span></div></div><div className="preview-chart cg-surface"><strong>이상점수 24h 추세</strong><svg viewBox="0 0 280 96" preserveAspectRatio="none"><path d="M0 78 C35 68 60 75 84 60 S122 66 145 48 S190 55 214 32 S252 42 280 12" fill="none" stroke="#ea580c" strokeWidth="2.5" /><path d="M0 78 C35 68 60 75 84 60 S122 66 145 48 S190 55 214 32 S252 42 280 12 L280 96 L0 96Z" fill="#ea580c" fillOpacity=".11" /></svg></div></div>}{preview === "failsafe" && <div className="preview-content preview-monitor"><div className="preview-pack cg-surface preview-failsafe"><span><AlertTriangle size={16} />임계값 초과 감지</span><strong>온도 임계값 초과</strong><Button variant="danger" onClick={openLogin}>릴레이 즉시 차단</Button><small>Fail-Safe 인터락 자동 실행 · 0.4초 내 응답</small></div><div className="preview-chart cg-surface"><strong>최근 이상 이벤트</strong><div className="preview-event"><i /><span><b>온도 임계값 초과</b><small>PACK-001 · 방금 전</small></span><em>위험</em></div></div></div>}</div></section>

      <section id="cta" className="v3-section v3-cta"><div className="cta-panel cg-glass"><span>THE MOMENT THAT MATTERS</span><h2>방심하는 그 순간, 셀가드는<br />이 순간을 막습니다.</h2><p>경고가 알림으로 끝나지 않도록, 임계값을 넘는 순간 릴레이가 자동으로 차단됩니다.</p><Button variant="primary" onClick={openLogin}>무료로 시작하기</Button></div></section>
    </main><footer className="public-footer"><Logo /><span>© 2026 셀가드. All rights reserved.</span></footer>
  </div>;
}

export function LoginPage({ onSuccess }: { onSuccess: () => Promise<void> }) {
  const navigate = useNavigate();
  const [serverError, setServerError] = useState("");
  const form = useForm<LoginValues>({ resolver: zodResolver(loginSchema), defaultValues: { email: "", password: "" } });
  const submit = form.handleSubmit(async (values) => { setServerError(""); try { await api.signIn(values.email, values.password); await onSuccess(); } catch (error) { setServerError(error instanceof ApiError && error.code === "ACCOUNT_SUSPENDED" ? "정지된 계정입니다. 관리자에게 문의하세요." : "이메일 또는 비밀번호를 확인하세요."); } });
  const adminLogin = async () => { setServerError(""); try { await api.signIn("lee@lab.io", "demo-password"); await onSuccess(); } catch { setServerError("관리자 로그인에 실패했습니다."); } };
  return <div className="auth-page login-auth-page"><div className="login-illustration"><Link to="/"><Logo inverse /></Link><div><h1>터지기 전에<br />먼저 잡는<br />배터리 관제</h1><p>1초 단위 실시간 모니터링과 AI 이상탐지로 열폭주를 조기에 경고합니다.</p></div><small>© 2026 셀가드 관제 시스템</small></div><main className="auth-card-wrap"><section className="auth-card auth-login-card"><div className="auth-heading"><Logo /><h2 aria-label="로그인">다시 오신 걸 환영합니다</h2><p>계정으로 로그인하고 관제를 시작하세요.</p></div><form onSubmit={submit} className="form-stack"><Field label="이메일"><input {...form.register("email")} type="email" autoComplete="email" placeholder="name@company.com" /></Field><Field label="비밀번호"><input {...form.register("password")} type="password" autoComplete="current-password" placeholder="비밀번호" /></Field>{serverError && <p className="form-error" role="alert">{serverError}</p>}<Button type="submit" variant="primary" loading={form.formState.isSubmitting} className="full-width">로그인</Button><button type="button" className="button button-secondary" aria-label="관리자 콘솔" onClick={() => void adminLogin()}><ShieldCheck size={16} />관리자 로그인</button></form><div className="auth-divider"><span />또는<span /></div><div className="social-actions"><Button type="button" variant="secondary" onClick={() => setServerError("Google 로그인은 외부 인증 연동 후 사용할 수 있습니다.")}>Google</Button><Button type="button" variant="secondary" onClick={() => navigate("/signup")}>회원가입</Button></div><div className="auth-links"><button className="text-button" onClick={() => navigate("/find")}>비밀번호 재설정</button><span>·</span><button className="text-button" onClick={() => navigate("/find")}>이메일(아이디) 찾기</button></div><p className="auth-back"><Link to="/">← 처음으로</Link></p></section></main></div>;
}

export function SignupPage() {
  const navigate = useNavigate();
  const [serverError, setServerError] = useState(""); const [done, setDone] = useState(false); const [emailChecked, setEmailChecked] = useState(false);
  const form = useForm<SignupValues>({ resolver: zodResolver(signupSchema), defaultValues: { name: "", email: "", phone: "", password: "", agreed: false } });
  const submit = form.handleSubmit(async (values) => { setServerError(""); try { await api.signUp({ name: values.name, email: values.email, phone: values.phone, password: values.password, termsVersion: "2026-08-06", privacyVersion: "2026-08-06", acceptedAt: new Date().toISOString() }); setDone(true); } catch (error) { setServerError(error instanceof ApiError ? "가입을 완료하지 못했습니다. 입력값을 확인하세요." : "네트워크 상태를 확인하세요."); } });
  if (done) return <div className="auth-page single"><main className="auth-card-wrap"><section className="auth-card"><div className="success-state"><div className="success-icon"><Check size={28} /></div><h1>가입 요청이 접수되었습니다.</h1><p>이메일 인증을 마치면 로그인할 수 있습니다.</p><Button variant="primary" onClick={() => navigate("/login")}>로그인으로 이동</Button></div></section></main></div>;
  return <div className="auth-page signup-auth-page"><div className="auth-aside"><Link to="/"><Logo inverse /></Link><div><h1>안전은,<br />예측에서 시작됩니다.</h1><p>가입 후 배터리를 등록하면 전압·전류·온도·SOC를 실시간으로 수집하고 AI가 이상 징후를 조기에 알려드립니다.</p></div><div className="auth-feature-list"><span><BatteryCharging size={18} />1초 단위 실시간 모니터링</span><span><AlertTriangle size={18} />AI 열폭주 조기 경고</span><span><ShieldCheck size={18} />위험 시 자동 릴레이 차단</span></div></div><main className="auth-card-wrap"><section className="auth-card"><div className="auth-heading"><Logo /><h2>계정 만들기</h2><p>30초면 관제를 시작할 수 있어요.</p></div><form onSubmit={submit} className="form-stack"><Field label="이름"><input {...form.register("name")} autoComplete="name" placeholder="홍길동" /></Field><Field label="이메일"><div className="input-with-action"><input {...form.register("email", { onChange: () => setEmailChecked(false) })} type="email" autoComplete="email" placeholder="name@company.com" /><button type="button" onClick={() => setEmailChecked(true)}>중복확인</button></div><span className={`field-hint ${emailChecked ? "field-success" : ""}`}>{emailChecked ? "사용 가능한 이메일입니다." : " "}</span></Field><Field label="전화번호"><input {...form.register("phone")} type="tel" autoComplete="tel" placeholder="010-1234-5678" /></Field><Field label="비밀번호" hint="영문·숫자·특수문자 조합 8자 이상"><input {...form.register("password")} type="password" autoComplete="new-password" placeholder="8자 이상" /></Field><label className="checkbox-field"><input {...form.register("agreed")} type="checkbox" /><span>서비스 이용약관 및 개인정보 처리방침에 동의합니다.</span></label>{form.formState.errors.agreed?.message && <p className="field-error">{form.formState.errors.agreed.message}</p>}{serverError && <p className="form-error" role="alert">{serverError}</p>}<Button type="submit" variant="primary" loading={form.formState.isSubmitting} className="full-width">가입하고 시작하기</Button></form><p className="auth-back">이미 계정이 있으신가요? <button className="text-button" onClick={() => navigate("/login")}>로그인</button></p></section></main></div>;
}

export function FindPage() {
  const navigate = useNavigate(); const [tab, setTab] = useState<"password" | "email">("password"); const [message, setMessage] = useState(""); const [found, setFound] = useState(""); const [loading, setLoading] = useState(false); const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState("");
  const submit = async () => { setMessage(""); setFound(""); setLoading(true); try { if (tab === "password") { if (!email.includes("@")) throw new Error("이메일을 입력하세요."); await api.resetPassword(email); setMessage("재설정 요청을 접수했습니다. 가입 여부와 관계없이 같은 안내를 표시합니다."); } else { const result = await api.findEmail({ name, phone }); setFound(result.email ?? "확인된 계정이 없습니다."); } } catch { setMessage("요청을 처리하지 못했습니다. 입력값과 네트워크 상태를 확인하세요."); } finally { setLoading(false); } };
  return <div className="auth-page find-auth-page"><div className="auth-aside"><Link to="/"><Logo inverse /></Link><div><h1>계정 정보는<br />안전하게 보호됩니다.</h1><p>본인 확인 절차를 거쳐 계정을 안전하게 복구해드립니다.</p></div></div><main className="auth-card-wrap"><section className="auth-card find-card"><Link to="/"><Logo /></Link><div className="tabs" role="tablist"><button className={tab === "password" ? "active" : ""} onClick={() => { setTab("password"); setMessage(""); }} role="tab">비밀번호 재설정</button><button className={tab === "email" ? "active" : ""} onClick={() => { setTab("email"); setMessage(""); }} role="tab">이메일 찾기</button></div>{tab === "password" ? <div className="form-stack"><div><h1>비밀번호를 잊으셨나요?</h1><p className="page-description">가입한 이메일로 재설정 링크를 보내드립니다.</p></div><Field label="이메일"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="name@company.com" /></Field><Button variant="primary" loading={loading} onClick={() => void submit()} className="full-width">재설정 링크 보내기</Button></div> : <div className="form-stack"><div><h1>이메일(아이디)을 찾습니다</h1><p className="page-description">가입 시 등록한 이름과 전화번호로 이메일을 확인합니다.</p></div><Field label="이름"><input value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" placeholder="홍길동" /></Field><Field label="전화번호"><input value={phone} onChange={(event) => setPhone(event.target.value)} autoComplete="tel" placeholder="010-1234-5678" /></Field><Button variant="secondary" loading={loading} onClick={() => void submit()} className="full-width">본인 확인 후 이메일 찾기</Button>{found && <div className="found-email"><small>확인된 이메일</small><strong>{found}</strong></div>}</div>}{message && <p className="form-message" role="status">{message}</p>}<p className="auth-back"><button className="text-button" onClick={() => navigate("/login")}>← 로그인으로 돌아가기</button></p></section></main></div>;
}
