import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { zodResolver } from "@hookform/resolvers/zod";
import { ArrowRight, Check, ChevronRight, ShieldCheck, Thermometer, Zap } from "lucide-react";
import { Link, useNavigate } from "react-router-dom";
import { api, ApiError } from "../api/client";
import { Button, Card, Field, Logo } from "../components/ui";
import { PublicHeader } from "../components/Shell";

const loginSchema = z.object({ email: z.string().email("이메일 형식을 확인하세요."), password: z.string().min(1, "비밀번호를 입력하세요.") });
type LoginValues = z.infer<typeof loginSchema>;
const signupSchema = z.object({ name: z.string().min(1, "이름을 입력하세요."), email: z.string().email("이메일 형식을 확인하세요."), phone: z.string().min(8, "전화번호를 입력하세요."), password: z.string().regex(/^(?=.*[A-Za-z])(?=.*\d)(?=.*[^A-Za-z\d]).{8,}$/, "영문·숫자·특수문자를 포함한 8자 이상이어야 합니다."), agreed: z.boolean().refine((value) => value, "약관 동의가 필요합니다.") });
type SignupValues = z.infer<typeof signupSchema>;

export function LandingPage() {
  const navigate = useNavigate();
  return <div className="public-page"><PublicHeader onLogin={() => navigate("/login")} onSignUp={() => navigate("/signup")} /><main className="landing-main"><section className="landing-hero"><div className="hero-copy"><p className="eyebrow">BATTERY SAFETY OBSERVABILITY</p><h1>배터리의 이상을<br /><span>더 일찍</span> 발견하세요.</h1><p>전압·전류·온도·SOC를 한 화면에서 관제하고<br />AI 이상탐지와 독립 Fail-Safe로 위험을 줄입니다.</p><div className="hero-actions"><Button variant="primary" onClick={() => navigate("/signup")}>관제 시작하기 <ArrowRight size={16} /></Button><Button variant="ghost" onClick={() => document.getElementById("how")?.scrollIntoView({ behavior: "smooth" })}>서비스 살펴보기 <ChevronRight size={16} /></Button></div><div className="hero-trust"><span><ShieldCheck size={16} /> 독립 안전계층</span><span><Zap size={16} /> 1초 단위 갱신</span><span><Check size={16} /> 감사 추적</span></div></div><div className="hero-visual"><div className="visual-glow" /><Card className="hero-dashboard"><div className="mini-head"><div><small>실시간 관제</small><strong>PACK-001 · 세션 진행 중</strong></div><span className="live-indicator"><span />LIVE</span></div><div className="mini-alert grade-warning"><span className="grade-shape triangle" /><div><strong>주의 · 이상점수 상승</strong><small>추세를 주시하세요.</small></div><b className="mono">58</b></div><div className="mini-metrics"><div><span>전압</span><strong className="mono">11.9 V</strong></div><div><span>전류</span><strong className="mono">2.4 A</strong></div><div><span>온도</span><strong className="mono">58.0 °C</strong></div><div><span>SOC</span><strong className="mono">78 %</strong></div></div><div className="mini-chart"><div className="chart-grid" /><svg viewBox="0 0 360 100" role="img" aria-label="이상점수 추세"><path d="M0 82 C35 68 52 74 78 57 S120 61 144 47 S187 58 218 35 S255 42 282 27 S330 32 360 12" fill="none" stroke="var(--primary)" strokeWidth="3" strokeLinecap="round" /></svg></div><div className="mini-footer"><span><span className="status-dot online" />데이터 수신 정상</span><span className="mono">2026.08.06 10:32:10</span></div></Card></div></section><section id="how" className="landing-section"><div className="section-heading"><p className="eyebrow">HOW IT WORKS</p><h2>위험을 읽는 세 가지 층</h2><p>데이터를 모으고, 이상을 해석하고, 안전계층이 독립적으로 개입합니다.</p></div><div className="feature-grid"><Card><div className="feature-icon blue"><Zap size={20} /></div><h3>센서 데이터 수집</h3><p>전압·전류·온도·SOC 원시값을 세션과 함께 기록합니다.</p></Card><Card><div className="feature-icon violet"><Thermometer size={20} /></div><h3>AI 이상탐지</h3><p>LSTM-AutoEncoder와 Informer가 현재 이상과 미래 위험을 분석합니다.</p></Card><Card><div className="feature-icon slate"><ShieldCheck size={20} /></div><h3>독립 Fail-Safe</h3><p>AI 결과와 분리된 안전계층이 조건 충족 시 릴레이를 차단합니다.</p></Card></div></section></main><footer className="public-footer"><Logo /><span>배터리 안전을 더 선명하게.</span></footer></div>;
}

export function LoginPage({ onSuccess }: { onSuccess: () => Promise<void> }) {
  const navigate = useNavigate();
  const [serverError, setServerError] = useState("");
  const form = useForm<LoginValues>({ resolver: zodResolver(loginSchema), defaultValues: { email: "", password: "" } });
  const submit = form.handleSubmit(async (values) => { setServerError(""); try { await api.signIn(values.email, values.password); await onSuccess(); } catch (error) { setServerError(error instanceof ApiError && error.code === "ACCOUNT_SUSPENDED" ? "정지된 계정입니다. 관리자에게 문의하세요." : "이메일 또는 비밀번호를 확인하세요."); } });
  return <div className="auth-page"><div className="auth-aside"><Link to="/"><Logo inverse /></Link><div><p className="eyebrow">CELLGUARD</p><h1>안전한 관제는<br />정확한 연결에서 시작됩니다.</h1><p>배터리를 연결하면 실시간 데이터와 이상탐지를 한 화면에서 확인할 수 있습니다.</p></div><div className="auth-aside-note"><ShieldCheck size={18} /><span>모든 위험 제어는 재인증과 사유 입력을 거칩니다.</span></div></div><main className="auth-card-wrap"><Card className="auth-card"><div className="auth-heading"><Logo /><h2>로그인</h2><p>셀가드 관제 화면에 로그인하세요.</p></div><form onSubmit={submit} className="form-stack"><Field label="이메일" error={form.formState.errors.email?.message}><input {...form.register("email")} type="email" autoComplete="email" placeholder="name@company.com" /></Field><Field label="비밀번호" error={form.formState.errors.password?.message}><input {...form.register("password")} type="password" autoComplete="current-password" placeholder="비밀번호" /></Field>{serverError && <p className="form-error" role="alert">{serverError}</p>}<Button type="submit" variant="primary" loading={form.formState.isSubmitting} className="full-width">로그인</Button></form><div className="auth-links"><button className="text-button" onClick={() => navigate("/find")}>비밀번호·이메일 찾기</button><span>·</span><button className="text-button" onClick={() => navigate("/signup")}>회원가입</button></div><p className="auth-back"><Link to="/">← 처음으로</Link></p></Card></main></div>;
}

export function SignupPage() {
  const navigate = useNavigate();
  const [serverError, setServerError] = useState("");
  const [done, setDone] = useState(false);
  const form = useForm<SignupValues>({ resolver: zodResolver(signupSchema), defaultValues: { name: "", email: "", phone: "", password: "", agreed: false } });
  const submit = form.handleSubmit(async (values) => { setServerError(""); try { await api.signUp({ name: values.name, email: values.email, phone: values.phone, password: values.password, termsVersion: "2026-08-06", privacyVersion: "2026-08-06", acceptedAt: new Date().toISOString() }); setDone(true); } catch (error) { setServerError(error instanceof ApiError ? "가입을 완료하지 못했습니다. 입력값을 확인하세요." : "네트워크 상태를 확인하세요."); } });
  if (done) return <div className="auth-page single"><main className="auth-card-wrap"><Card className="auth-card"><div className="success-state"><div className="success-icon"><Check size={28} /></div><h1>가입 요청이 접수되었습니다.</h1><p>이메일 인증을 마치면 로그인할 수 있습니다.</p><Button variant="primary" onClick={() => navigate("/login")}>로그인으로 이동</Button></div></Card></main></div>;
  return <div className="auth-page"><div className="auth-aside"><Link to="/"><Logo inverse /></Link><div><p className="eyebrow">START IN 30 SECONDS</p><h1>배터리의 상태를<br />한눈에 관리하세요.</h1><p>가입 후 배터리 자산을 등록하고 첫 측정 세션을 시작할 수 있습니다.</p></div></div><main className="auth-card-wrap"><Card className="auth-card"><div className="auth-heading"><Logo /><h2>계정 만들기</h2><p>30초면 관제를 시작할 수 있어요.</p></div><form onSubmit={submit} className="form-stack"><Field label="이름" error={form.formState.errors.name?.message}><input {...form.register("name")} autoComplete="name" placeholder="홍길동" /></Field><Field label="이메일" error={form.formState.errors.email?.message}><input {...form.register("email")} type="email" autoComplete="email" placeholder="name@company.com" /></Field><Field label="전화번호" error={form.formState.errors.phone?.message}><input {...form.register("phone")} type="tel" autoComplete="tel" placeholder="010-1234-5678" /></Field><Field label="비밀번호" hint="영문·숫자·특수문자를 포함한 8자 이상" error={form.formState.errors.password?.message}><input {...form.register("password")} type="password" autoComplete="new-password" placeholder="비밀번호" /></Field><label className="checkbox-field"><input {...form.register("agreed")} type="checkbox" /><span>서비스 이용약관 및 개인정보 처리방침에 동의합니다.</span></label>{form.formState.errors.agreed?.message && <p className="field-error">{form.formState.errors.agreed.message}</p>}{serverError && <p className="form-error" role="alert">{serverError}</p>}<Button type="submit" variant="primary" loading={form.formState.isSubmitting} className="full-width">가입하고 시작하기</Button></form><p className="auth-back">이미 계정이 있으신가요? <button className="text-button" onClick={() => navigate("/login")}>로그인</button></p></Card></main></div>;
}

export function FindPage() {
  const navigate = useNavigate();
  const [tab, setTab] = useState<"password" | "email">("password");
  const [message, setMessage] = useState("");
  const [found, setFound] = useState("");
  const [loading, setLoading] = useState(false);
  const [email, setEmail] = useState(""); const [name, setName] = useState(""); const [phone, setPhone] = useState("");
  const submit = async () => { setMessage(""); setFound(""); setLoading(true); try { if (tab === "password") { if (!email.includes("@")) throw new Error("이메일을 입력하세요."); await api.resetPassword(email); setMessage("재설정 요청을 접수했습니다. 가입 여부와 관계없이 같은 안내를 표시합니다."); } else { const result = await api.findEmail({ name, phone }); setFound(result.email ?? "확인된 계정이 없습니다."); } } catch { setMessage("요청을 처리하지 못했습니다. 입력값과 네트워크 상태를 확인하세요."); } finally { setLoading(false); } };
  return <div className="auth-page single"><main className="auth-card-wrap"><Card className="auth-card find-card"><Link to="/"><Logo /></Link><div className="tabs"><button className={tab === "password" ? "active" : ""} onClick={() => { setTab("password"); setMessage(""); }}>비밀번호 재설정</button><button className={tab === "email" ? "active" : ""} onClick={() => { setTab("email"); setMessage(""); }}>이메일 찾기</button></div>{tab === "password" ? <div className="form-stack"><div><h1>비밀번호를 잊으셨나요?</h1><p className="page-description">가입한 이메일로 재설정 링크를 보내드립니다.</p></div><Field label="이메일"><input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" placeholder="name@company.com" /></Field><Button variant="primary" loading={loading} onClick={() => void submit()} className="full-width">재설정 링크 보내기</Button></div> : <div className="form-stack"><div><h1>이메일(아이디)을 찾습니다</h1><p className="page-description">가입 시 등록한 이름과 전화번호로 확인합니다.</p></div><Field label="이름"><input value={name} onChange={(event) => setName(event.target.value)} autoComplete="name" placeholder="홍길동" /></Field><Field label="전화번호"><input value={phone} onChange={(event) => setPhone(event.target.value)} autoComplete="tel" placeholder="010-1234-5678" /></Field><Button variant="secondary" loading={loading} onClick={() => void submit()} className="full-width">본인 확인 후 이메일 찾기</Button>{found && <div className="found-email"><small>확인된 이메일</small><strong>{found}</strong></div>}</div>}{message && <p className="form-message" role="status">{message}</p>}<p className="auth-back"><button className="text-button" onClick={() => navigate("/login")}>← 로그인으로 돌아가기</button></p></Card></main></div>;
}
